#! /bin/bash
## $HOME/.config/bash/environment
## by Andrew Velez

HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s checkwinsize

if [[ -x /usr/bin/dircolors ]]; then
  (test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)") || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
fi

export TERM="xterm-256color"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local"
export NVM_DIR="$HOME/.local/nvm"
export RUSTUP_HOME="$HOME/.local/rustup"
export CARGO_HOME="$HOME/.local/cargo"
export DOTNET_ROOT="$HOME/.local/dotnet"
export GOPATH="$HOME/.local/go"
export RUBY_HOME="$HOME/.local/share/gem/ruby/3.4.0"
export LOGGER_LEVEL="3"

XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/flatpak/exports/share"
av:add-path "$HOME/.local/bin" "$DOTNET_ROOT" "$DOTNET_ROOT/tools" "$RUBY_HOME/bin" "$GOPATH/bin"

# Source all the things!
[[ $- == *i* ]] && [[ -r "$HOME/.local/share/blesh/ble.sh" ]] && . "$HOME/.local/share/blesh/ble.sh" --attach=none
type -t "oh-my-posh" >/dev/null && eval "$(oh-my-posh init bash --config "$HOME"/.config/posh/onehalf.modified.omp.json)"
type -t "batman" >/dev/null && eval "$(batman --export-env)"
type -t "jj" >/dev/null && eval "$(jj util completion bash)"
[[ -r "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
[[ -r "$NVM_DIR/bash_completion" ]] && . "$NVM_DIR/bash_completion"
[[ -r "$CARGO_HOME/env" ]] && . "$CARGO_HOME/env"
[[ -r "$HOME/.rbenv/bin/rbenv" ]] && eval "$("$HOME"/.rbenv/bin/rbenv init - --no-rehash bash)"
eval "$(ssh-agent -s)" >/dev/null